/*
 * Principal.java
 *
 * Created on 29 mars 2010, 13:59:56
 */
package Interface;

import java.awt.BorderLayout;

/**
 *
 * @author grandj
 */
public class Principal extends javax.swing.JFrame {

    Canvas can;

    /** Creates new form Principal */
    public Principal() {
        initComponents();

        can = new Canvas();
        jPanelSupport.setLayout(new BorderLayout());
        jPanelSupport.add(can, BorderLayout.CENTER);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jPanelSupport = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemQuitter = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemRAZ = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(100, 25));
        jToolBar1.setMinimumSize(new java.awt.Dimension(100, 25));

        jLabel1.setText("Logiciel de dessin");
        jToolBar1.add(jLabel1);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_END);

        jPanelSupport.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanelSupportLayout = new javax.swing.GroupLayout(jPanelSupport);
        jPanelSupport.setLayout(jPanelSupportLayout);
        jPanelSupportLayout.setHorizontalGroup(
            jPanelSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );
        jPanelSupportLayout.setVerticalGroup(
            jPanelSupportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelSupport, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        jMenuItemQuitter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemQuitter.setText("Quitter");
        jMenu1.add(jMenuItemQuitter);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItemRAZ.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemRAZ.setText("Remise à zéro");
        jMenuItemRAZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRAZActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemRAZ);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemRAZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRAZActionPerformed
        can.remiseAZero();
    }//GEN-LAST:event_jMenuItemRAZActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemQuitter;
    private javax.swing.JMenuItem jMenuItemRAZ;
    private javax.swing.JPanel jPanelSupport;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
